var studentsName = ["dildara", "saima", "naeema",];
console.log(studentsName);
studentsName.push("ruqaiya");
console.log(studentsName);
studentsName.pop();
console.log(studentsName);
studentsName.unshift("ruqaiya");
console.log(studentsName);
studentsName.shift();
console.log(studentsName);
